### ISSUE TITLE
error: link.exe not found

### ISSUE THREAD

**Issue by Pleezon** [moonrepo/setup-rust#11]
![image](https://github.com/moonrepo/setup-rust/assets/56537983/4e45bd97-f5ed-4925-b683-b78ee20c628c)

Hey, this might just be me not knowing what I'm doing, but I've tried a fair bit of things and none of them seemed to help.
workflow:

```
      - uses: moonrepo/setup-rust@v1
        with:
          profile: complete
          targets: 'x86_64-pc-windows-msvc,x86_64-pc-windows-gnu'
      - name: Build exe/
        run: cargo build --release --all-features --manifest-path exe/Cargo.toml --target=x86_64-pc-windows-msvc
```
