### ISSUE TITLE
Fails to cache on macos-13

### ISSUE THREAD

**Issue by flaviojs** [moonrepo/setup-rust#18]
The post step of this github action fails on macos-13 with:
> Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

No idea what command line is being tried, it is printed in the other 2 successful cases but not in this case.

Workflow (clipped):
```
# ...
jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    # ...
    - name: Install dependencies (rust)
      uses: moonrepo/setup-rust@v1
      with:
        targets: x86_64-unknown-linux-gnu
        components: clippy,rustfmt
    # ...

  build-macos:
    name: MacOS
    runs-on: macos-13 # macos-latest/macos-14 has an ARM cpu (Apple M1) but we want an AMD64 cpu
    steps:
    # ...
    - name: Install dependencies (rust)
      uses: moonrepo/setup-rust@v1
      with:
        targets: x86_64-apple-darwin
        components: clippy,rustfmt
    # ...

  build-cygwin:
    name: Cygwin
    runs-on: windows-latest
    steps:
    # ...
    - name: Install dependencies (rust)
      uses: moonrepo/setup-rust@v1
      with:
        targets: x86_64-pc-windows-gnu
        components: clippy,rustfmt
    # ...
```
