### ISSUE TITLE
Windows: `Can't find crate for core`

### ISSUE THREAD

**Issue by JonnyBurger** [moonrepo/setup-rust#7]
Hi!

We are looking to adopt this package and migrate from actions-rs.
On Windows, the compilation fails due to:

```
error[E0463]: can't find crate for `core`
```
CI run:
https://github.com/remotion-dev/remotion/actions/runs/4890840629/jobs/8730672600?pr=2189

Configuration: `channel: "1.67.1", profile: minimal`

Since this package wants to be a migration path from actions-rs, I thought I raise an issue.

**Comment by milesj** [comment]
@JonnyBurger Seems like the error says you need `x86_64-pc-windows-gnu`? Have you tried adding that to the `targets` list?

**Comment by JonnyBurger** [comment]
Thanks a lot for answering!

How would one specify that?

The following does not work:

```yml
      - uses: moonrepo/setup-rust@v0
        with:
          channel: "1.67.1"
          profile: minimal
          targets:
            - x86_64-pc-windows-gnu
```

and there seems to be no documentation about `targets`.

I was running the command on Windows, so it would be nice if this were the default target - this worked automatically in actions-rs/setup-rs

**Comment by milesj** [comment]
@JonnyBurger The value is a string, so probably this:

```
      - uses: moonrepo/setup-rust@v0
        with:
          channel: "1.67.1"
          profile: minimal
          targets: x86_64-pc-windows-gnu
```

I'll update the docs.
